
#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_MTV3D_DIALOG	102
#define IDD_ABOUTBOX			103

#define IDM_NEW_PROJ		11
#define IDM_EXIT			12
#define IDM_CLOSE_PROJ		13
#define IDM_DOC				32
#define IDM_ABOUT			31

#define BUTTON_NEW_PROJ		1
#define BUTTON_CLOSE_SEL	2
#define BUTTON_CLOSE_ALL	3
#define BUTTON_CREATE_PLANE 4

#define CHECK_GRID		10
#define CHECK_AX_VAL	11

#define ID_LISTVIEW  70

#define IDI_MTV3D			107
#define IDC_MTV3D			109
#define IDC_MTV3D_VIS		110

#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif

#define IDT_TIMER_SPLASH	121



#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
